### ISSUE TITLE
Question about the number of the examples of test dataset in E2E-ABSA task

### ISSUE THREAD

**Issue by Bigggapple** [NUSTM/ChatGPT-Sentiment-Evaluation#3]
Hi, I noticed the statistics in Table 2 of your paper and found that the number of test instances for the E2E-ABSA task is inconsistent with the Sem14 test dataset. In the paper by Pontiki et al. (2014), the test size for the laptop and restaurant domains is stated as 800 sentences each. However, in Table 2, the numbers are changed to 339 and 496, and you mentioned in your paper that you used the entire test set. Therefore, I am curious about the differences here.

**Comment by SinclairCoder** [comment]
Sorry for the late reply. After check, the test sets of E2E-ABSA we used were derived from [Peng et al. 2021., AAAI](https://arxiv.org/pdf/1911.01616.pdf). We will update this to make it clear in our revision.

**Comment by Bigggapple** [comment]
Thank you for your response. I understand the situation now. Your clarification has been helpful.
